logging:
  level: INFO
  loggers:
    com.miniqueue: DEBUG
# Database settings.
database:

    # the name of the JDBC driver, mysql in our case

    driverClass: com.mysql.jdbc.Driver

    # the username

    user: root

    # the password

    password: root

    # the JDBC URL; the database is called DWGettingStarted

    url: jdbc:mysql://localhost:3306/miniq_db

logging:
  level: INFO
  loggers:
    "org.skife.jdbi.v2": TRACE
    
messageQueue:
  timeout: 60